export const CRISIS_KEYWORDS = [
  "he's here",
  "he is here",
  "they're here",
  "they are here",
  "someone is here",
  "someone's here",
  "he's coming",
  "he is coming",
  "they're coming",
  "they are coming",
  "outside the door",
  "at the door",
  "help",
  "i'm scared",
  "i am scared",
  "i feel unsafe",
  "i'm not safe",
  "i am not safe",
  "panic",
  "please help",
  "he's outside",
  "he is outside",
  "they're outside",
  "someone is outside",
  "following me",
  "wo yahan hai",
  "koi yahan hai",
  "mujhe darr lag raha hai",
  "madad chahiye",
  "dar lag raha hai",
  "safe nahi hoon",
  "ayuda",
  "tengo miedo",
  "no estoy segura",
  "no estoy seguro",
  "esta aqui",
  "esta afuera",
];
